services:
  postgres:
    image: postgres:16-alpine
    container_name: bond-postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME:-bond_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-bond_pass}
      POSTGRES_DB: ${DB_NAME:-bond_db}
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: bond-pgadmin
    restart: unless-stopped
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bond.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres

volumes:
  pgdata:
